# Generated by Django 2.0 on 2018-01-11 10:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BroadCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=126, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(max_length=126, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentBroadCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.BroadCategory')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentCrop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Crop')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Design')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentIUCNAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentIUCNHabitat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentIUCNThreat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentLatLong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.FloatField(validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentPopulation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='ExperimentTaxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='Intervention',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intervention', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IUCNActionLevel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IUCNActionLevel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=254)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.IUCNActionLevel1')),
            ],
        ),
        migrations.CreateModel(
            name='IUCNActionLevel3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=254)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.IUCNActionLevel2')),
            ],
        ),
        migrations.CreateModel(
            name='IUCNHabitatLevel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IUCNHabitatLevel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitat', models.CharField(max_length=254)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.IUCNHabitatLevel1')),
            ],
        ),
        migrations.CreateModel(
            name='IUCNThreatLevel1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='IUCNThreatLevel2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threat', models.CharField(max_length=254)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.IUCNThreatLevel1')),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=510)),
                ('abstract', models.TextField(blank=True)),
                ('authors', models.TextField(blank=True)),
                ('year', models.CharField(blank=True, max_length=30)),
                ('journal', models.CharField(blank=True, max_length=510)),
                ('volume', models.CharField(blank=True, max_length=30)),
                ('issue', models.CharField(blank=True, max_length=30)),
                ('pages', models.CharField(blank=True, max_length=30)),
                ('doi', models.CharField(blank=True, max_length=510)),
                ('url', models.CharField(blank=True, max_length=510)),
                ('publisher', models.CharField(blank=True, max_length=510)),
                ('place', models.CharField(blank=True, max_length=510)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(max_length=126)),
                ('family', models.CharField(max_length=126)),
                ('genus', models.CharField(max_length=126)),
                ('species', models.CharField(max_length=126)),
            ],
        ),
        migrations.AddField(
            model_name='experimenttaxon',
            name='taxon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Taxon'),
        ),
        migrations.AddField(
            model_name='experimentpopulation',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Population'),
        ),
        migrations.AddField(
            model_name='experimentiucnthreat',
            name='threat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.IUCNThreatLevel2'),
        ),
        migrations.AddField(
            model_name='experimentiucnhabitat',
            name='habitat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.IUCNHabitatLevel2'),
        ),
        migrations.AddField(
            model_name='experimentiucnaction',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.IUCNActionLevel3'),
        ),
        migrations.AddField(
            model_name='experimentiucnaction',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Experiment'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='intervention',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Intervention'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication'),
        ),
        migrations.AlterUniqueTogether(
            name='experimentcrop',
            unique_together={('experiment', 'crop')},
        ),
    ]
