# Generated by Django 2.0 on 2018-01-11 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PopulationOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Outcome')),
                ('population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Population')),
            ],
        ),
        migrations.RenameField(
            model_name='experimentbroadcategory',
            old_name='category',
            new_name='broad_category',
        ),
    ]
