# Generated by Django 2.0 on 2018-02-08 09:03

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20180207_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='publications.Intervention'),
        ),
        migrations.AddField(
            model_name='intervention',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervention',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intervention',
            name='intervention',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='intervention',
            unique_together={('intervention', 'parent')},
        ),
    ]
