# Generated by Django 2.0 on 2018-01-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_auto_20180111_1219'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentPopulationOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment_population', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.ExperimentPopulation')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Outcome')),
            ],
        ),
        migrations.RemoveField(
            model_name='populationoutcome',
            name='outcome',
        ),
        migrations.RemoveField(
            model_name='populationoutcome',
            name='population',
        ),
        migrations.DeleteModel(
            name='PopulationOutcome',
        ),
    ]
