# Generated by Django 2.0 on 2018-01-11 13:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20180111_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='effect_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='n_control',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='n_total',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='n_treatment',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='p_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='sd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='se',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='significant',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='variance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='z_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='sign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Sign'),
        ),
    ]
