# Generated by Django 2.0 on 2018-01-11 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20180111_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='Effect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='experimentpopulationoutcome',
            name='sign',
        ),
        migrations.DeleteModel(
            name='Sign',
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='effect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Effect'),
        ),
    ]
