# Generated by Django 2.0 on 2018-04-05 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20180405_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
