# Generated by Django 2.0 on 2018-01-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_auto_20180111_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='approximate_p_value',
            field=models.FloatField(blank=True, choices=[(0.0001, '< 0.0001'), (0.001, '< 0.001'), (0.01, '< 0.01'), (0.05, '< 0.05'), (0.1, '< 0.1'), (0.05, '> 0.05'), (0.1, '> 0.1')], null=True),
        ),
    ]
