# Generated by Django 2.0 on 2018-04-06 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0005_subject_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Subject'),
        ),
    ]
