# Generated by Django 2.0 on 2018-04-06 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_publication_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_relevant', models.BooleanField()),
                ('assessor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Subject')),
            ],
        ),
    ]
