# Generated by Django 2.0 on 2018-01-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_experimentpopulationoutcome_approximate_p_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentpopulationoutcome',
            name='approximate_p_value',
            field=models.CharField(blank=True, choices=[('< 0.0001', '< 0.0001'), ('< 0.001', '< 0.001'), ('< 0.01', '< 0.01'), ('< 0.05', '< 0.05'), ('< 0.1', '< 0.1'), ('> 0.05', '> 0.05'), ('> 0.1', '> 0.1')], max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='experimentpopulationoutcome',
            name='effect',
            field=models.IntegerField(blank=True, choices=[(1, '+'), (0, '0'), (-1, '-')], null=True),
        ),
        migrations.DeleteModel(
            name='Effect',
        ),
    ]
