# Generated by Django 2.0 on 2018-01-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20180111_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentpopulationoutcome',
            old_name='p_value',
            new_name='exact_p_value',
        ),
        migrations.RenameField(
            model_name='experimentpopulationoutcome',
            old_name='n_total',
            new_name='n',
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='control_mean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='effect_size_unit',
            field=models.CharField(blank=True, choices=[('g', "g - Hedges' g (standardized mean difference)"), ('R', 'R - Response ratio'), ('L', 'L - Log response ratio'), ('Zr', "Zr - Fischer's Z-transformed r")], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='other_unit',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='sd_control',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='sd_treatment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='se_control',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='se_treatment',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='sed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='treatment_mean',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='experimentpopulationoutcome',
            name='unit',
            field=models.CharField(blank=True, max_length=62, null=True),
        ),
    ]
