# Generated by Django 2.0 on 2018-04-06 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_assessment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessment',
            old_name='assessor',
            new_name='user',
        ),
    ]
