# Generated by Django 2.0 on 2018-07-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_assessment_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
