# Generated by Django 2.0 on 2018-01-11 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20180111_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentpopulationoutcome',
            name='exact_p_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
