# Generated by Django 2.0 on 2018-07-20 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_publication_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentstatus',
            name='next_full_text_assessment',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
