# Generated by Django 2.0 on 2018-05-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_assessmentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervention',
            name='code',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
