# Generated by Django 2.0 on 2018-01-11 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0009_auto_20180111_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentpopulationoutcome',
            name='exact_p_value',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
    ]
