# Generated by Django 2.0 on 2018-05-24 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_intervention_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcome',
            name='code',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
