# Generated by Django 2.0 on 2018-07-23 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0010_assessment_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentstatus',
            old_name='next_full_text_assessment',
            new_name='last_full_text_assessment',
        ),
        migrations.RemoveField(
            model_name='assessmentstatus',
            name='completed_full_text_assessments',
        ),
        migrations.RemoveField(
            model_name='assessmentstatus',
            name='relevant_publications',
        ),
    ]
