# Generated by Django 2.0 on 2018-07-23 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_auto_20180723_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assessmentstatus',
            old_name='last_full_text_assessment',
            new_name='previous_full_text_assessment',
        ),
    ]
