# Generated by Django 2.0 on 2018-08-28 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0013_publicationcountry_publicationdate_publicationlatlong_publicationpopulation_publicationpopulationout'),
    ]

    operations = [
        migrations.AddField(
            model_name='experimentpopulation',
            name='new_population',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Outcome'),
        ),
    ]
