# Generated by Django 2.0 on 2018-08-28 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_experimentpopulation_new_population'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentpopulation',
            name='old_population',
        ),
        migrations.RemoveField(
            model_name='experimentpopulation',
            name='population',
        ),
    ]
