# Generated by Django 2.0 on 2018-06-05 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0014_auto_20180529_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
