# Generated by Django 2.0 on 2018-08-28 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_auto_20180828_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentpopulation',
            old_name='new_population',
            new_name='population',
        ),
    ]
