# Generated by Django 2.0 on 2018-06-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0015_assessment_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='full_text_is_relevant',
            field=models.NullBooleanField(),
        ),
    ]
