# Generated by Django 2.0 on 2018-06-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_assessment_full_text_is_relevant'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentstatus',
            name='completed_full_text_assessments',
            field=models.TextField(blank=True),
        ),
    ]
