# Generated by Django 2.0 on 2018-08-30 14:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0016_auto_20180828_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentLatLongDMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_degrees', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(90.0)])),
                ('latitude_minutes', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)])),
                ('latitude_seconds', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)])),
                ('latitude_direction', models.CharField(blank=True, choices=[('N', 'N'), ('S', 'S')], default='N', max_length=10, null=True)),
                ('longitude_degrees', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(180.0)])),
                ('longitude_minutes', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)])),
                ('longitude_seconds', models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(60.0)])),
                ('longitude_direction', models.CharField(blank=True, choices=[('E', 'E'), ('W', 'W')], default='E', max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Experiment')),
            ],
        ),
        migrations.CreateModel(
            name='PublicationLatLongDMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude_degrees', models.FloatField(blank=True, default=None, null=True)),
                ('latitude_minutes', models.FloatField(blank=True, default=None, null=True)),
                ('latitude_seconds', models.FloatField(blank=True, default=None, null=True)),
                ('latitude_direction', models.CharField(blank=True, choices=[('N', 'N'), ('S', 'S')], default='N', max_length=10, null=True)),
                ('longitude_degrees', models.FloatField(blank=True, default=None, null=True)),
                ('longitude_minutes', models.FloatField(blank=True, default=None, null=True)),
                ('longitude_seconds', models.FloatField(blank=True, default=None, null=True)),
                ('longitude_direction', models.CharField(blank=True, choices=[('E', 'E'), ('W', 'W')], default='E', max_length=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Publication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Population',
        ),
        migrations.AlterField(
            model_name='experimentlatlong',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='experimentlatlong',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
        migrations.AlterField(
            model_name='publicationlatlong',
            name='latitude',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)]),
        ),
        migrations.AlterField(
            model_name='publicationlatlong',
            name='longitude',
            field=models.FloatField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)]),
        ),
    ]
