# Generated by Django 2.0 on 2019-02-04 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0018_auto_20190204_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='intervention',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Intervention'),
        ),
        migrations.AddField(
            model_name='subject',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Outcome'),
        ),
    ]
