# Generated by Django 2.0 on 2019-02-06 19:25

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0019_auto_20190204_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='level',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='lft',
            field=models.PositiveIntegerField(db_index=True, default=1, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='publications.Design'),
        ),
        migrations.AddField(
            model_name='design',
            name='rght',
            field=models.PositiveIntegerField(db_index=True, default=2, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='slug',
            field=models.SlugField(default='default', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='design',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='design',
            name='design',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
    ]
