# Generated by Django 2.0 on 2019-02-07 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0020_auto_20190206_1925'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='design',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='publications.Design'),
        ),
    ]
