# Generated by Django 2.0 on 2019-04-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0023_auto_20190329_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='eav',
            name='population',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EAV_population', to='publications.ExperimentPopulation'),
        ),
        migrations.AddField(
            model_name='eav',
            name='population_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EAV_population_index', to='publications.ExperimentPopulation'),
        ),
        migrations.AlterUniqueTogether(
            name='eav',
            unique_together={('attribute', 'population', 'user'), ('attribute', 'outcome', 'user'), ('attribute', 'experiment', 'user'), ('attribute', 'publication', 'user')},
        ),
    ]
