# Generated by Django 2.0 on 2019-04-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0024_auto_20190401_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='is_from_systematic_search',
            field=models.BooleanField(default=True),
        ),
    ]
