# Generated by Django 2.0 on 2019-04-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0025_publication_is_from_systematic_search'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experimentpopulationoutcome',
            name='control_mean',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experimentpopulationoutcome',
            name='treatment_mean',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
