# Generated by Django 2.0 on 2019-04-03 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0026_auto_20190402_1531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='experimentpopulationoutcome',
            old_name='n_control',
            new_name='control_n',
        ),
        migrations.RenameField(
            model_name='experimentpopulationoutcome',
            old_name='sd_control',
            new_name='control_sd',
        ),
        migrations.RenameField(
            model_name='experimentpopulationoutcome',
            old_name='exact_p_value',
            new_name='p_value',
        ),
        migrations.RenameField(
            model_name='experimentpopulationoutcome',
            old_name='n_treatment',
            new_name='treatment_n',
        ),
        migrations.RenameField(
            model_name='experimentpopulationoutcome',
            old_name='sd_treatment',
            new_name='treatment_sd',
        ),
        migrations.RemoveField(
            model_name='experimentpopulationoutcome',
            name='effect',
        ),
        migrations.RemoveField(
            model_name='experimentpopulationoutcome',
            name='se_control',
        ),
        migrations.RemoveField(
            model_name='experimentpopulationoutcome',
            name='se_treatment',
        ),
        migrations.AlterField(
            model_name='experimentpopulationoutcome',
            name='effect_size',
            field=models.FloatField(blank=True, help_text='As published, not as calculated from the data above', null=True),
        ),
        migrations.AlterField(
            model_name='experimentpopulationoutcome',
            name='effect_size_unit',
            field=models.CharField(blank=True, choices=[('d', 'Standardized mean difference (d)'), ('R', 'Response ratio (R)'), ('L', 'Log response ratio (L)'), ('r', 'Correlation coefficient (r)'), ('Zr', "Fischer's Z-transformed r (Zr)"), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
