# Generated by Django 2.0 on 2019-04-15 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0028_auto_20190403_1444'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExperimentLatLongDMS',
            new_name='Coordinates',
        ),
        migrations.AlterField(
            model_name='data',
            name='unit',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='experimentpopulation',
            name='population',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.Outcome'),
        ),
    ]
