# Generated by Django 2.0 on 2019-04-15 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0029_auto_20190415_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinates',
            name='experiment_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_experiment_index', to='publications.Experiment'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_outcome', to='publications.ExperimentPopulationOutcome'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='outcome_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_outcome_index', to='publications.ExperimentPopulationOutcome'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='population',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_population', to='publications.ExperimentPopulation'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='population_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_population_index', to='publications.ExperimentPopulation'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_publication', to='publications.Publication'),
        ),
        migrations.AddField(
            model_name='coordinates',
            name='publication_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_publication_index', to='publications.Publication'),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coordinates_experiment', to='publications.Experiment'),
        ),
    ]
