# Generated by Django 2.0 on 2019-04-16 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0030_auto_20190415_1130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentlatlong',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='publicationlatlong',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='publicationlatlong',
            name='user',
        ),
        migrations.RemoveField(
            model_name='publicationlatlongdms',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='publicationlatlongdms',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='coordinates',
            options={'verbose_name_plural': 'coordinates'},
        ),
        migrations.AddField(
            model_name='coordinates',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='latitude_direction',
            field=models.CharField(blank=True, choices=[('N', 'N (+)'), ('S', 'S (-)')], default='N', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='coordinates',
            name='longitude_direction',
            field=models.CharField(blank=True, choices=[('E', 'E (+)'), ('W', 'W (-)')], default='E', max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='ExperimentLatLong',
        ),
        migrations.DeleteModel(
            name='PublicationLatLong',
        ),
        migrations.DeleteModel(
            name='PublicationLatLongDMS',
        ),
    ]
