# Generated by Django 2.0 on 2019-04-16 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0032_xcountry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentcountry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='experimentcountry',
            name='experiment',
        ),
        migrations.RemoveField(
            model_name='publicationcountry',
            name='country',
        ),
        migrations.RemoveField(
            model_name='publicationcountry',
            name='publication',
        ),
        migrations.RemoveField(
            model_name='publicationcountry',
            name='user',
        ),
        migrations.DeleteModel(
            name='ExperimentCountry',
        ),
        migrations.DeleteModel(
            name='PublicationCountry',
        ),
    ]
