# Generated by Django 2.0 on 2019-04-17 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0033_auto_20190416_1658'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eav',
            unique_together=set(),
        ),
    ]
