# Generated by Django 2.0 on 2019-04-18 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0034_auto_20190417_0931'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PublicationDate',
            new_name='Date',
        ),
        migrations.RemoveField(
            model_name='experimentcrop',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='experimentcrop',
            name='experiment',
        ),
        migrations.DeleteModel(
            name='ExperimentCrop',
        ),
    ]
