# Generated by Django 2.0 on 2019-04-18 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0036_auto_20190418_1307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experimentdate',
            name='experiment',
        ),
        migrations.AlterField(
            model_name='date',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_experiment', to='publications.Experiment'),
        ),
        migrations.AlterField(
            model_name='date',
            name='experiment_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_experiment_index', to='publications.Experiment'),
        ),
        migrations.AlterField(
            model_name='date',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_outcome', to='publications.ExperimentPopulationOutcome'),
        ),
        migrations.AlterField(
            model_name='date',
            name='outcome_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_outcome_index', to='publications.ExperimentPopulationOutcome'),
        ),
        migrations.AlterField(
            model_name='date',
            name='population',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_population', to='publications.ExperimentPopulation'),
        ),
        migrations.AlterField(
            model_name='date',
            name='population_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_population_index', to='publications.ExperimentPopulation'),
        ),
        migrations.AlterField(
            model_name='date',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_publication', to='publications.Publication'),
        ),
        migrations.AlterField(
            model_name='date',
            name='publication_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='date_publication_index', to='publications.Publication'),
        ),
        migrations.DeleteModel(
            name='ExperimentDate',
        ),
    ]
