# Generated by Django 2.0 on 2019-04-26 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0037_auto_20190418_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='correlation_coefficient',
            field=models.FloatField(blank=True, help_text='Pearson correlation coefficient (r)', null=True, validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='effect_size_unit',
            field=models.CharField(blank=True, choices=[('d', 'Standardized mean difference (d)'), ('R', 'Response ratio (R)'), ('L', 'Log response ratio (L)'), ('r', 'Pearson correlation coefficient (r)'), ('Zr', "Fischer's Z-transformed r (Zr)"), ('Other', 'Other')], max_length=30, null=True),
        ),
    ]
