# Generated by Django 2.0 on 2019-05-01 14:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0039_auto_20190426_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='control_se',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='data',
            name='is_significant',
            field=models.NullBooleanField(choices=[(None, '---------'), (True, 'Yes'), (False, 'No')]),
        ),
        migrations.AddField(
            model_name='data',
            name='treatment_se',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='data',
            name='unit',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
