# Generated by Django 2.0 on 2019-05-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0040_auto_20190501_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='language_barrier',
            field=models.BooleanField(default=False),
        ),
    ]
