# Generated by Django 2.0 on 2019-05-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0041_assessment_language_barrier'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='study_name',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
