# Generated by Django 2.0 on 2019-05-15 14:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0043_auto_20190515_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study',
            name='experiment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_experiment', to='publications.Experiment'),
        ),
        migrations.AlterField(
            model_name='study',
            name='experiment_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_experiment_index', to='publications.Experiment'),
        ),
        migrations.AlterField(
            model_name='study',
            name='outcome',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_outcome', to='publications.ExperimentPopulationOutcome'),
        ),
        migrations.AlterField(
            model_name='study',
            name='outcome_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_outcome_index', to='publications.ExperimentPopulationOutcome'),
        ),
        migrations.AlterField(
            model_name='study',
            name='population',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_population', to='publications.ExperimentPopulation'),
        ),
        migrations.AlterField(
            model_name='study',
            name='population_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_population_index', to='publications.ExperimentPopulation'),
        ),
        migrations.AlterField(
            model_name='study',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_publication', to='publications.Publication'),
        ),
        migrations.AlterField(
            model_name='study',
            name='publication_index',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='study_publication_index', to='publications.Publication'),
        ),
        migrations.AlterField(
            model_name='study',
            name='study_id',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
