# Generated by Django 2.0 on 2019-07-11 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0044_auto_20190515_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubject',
            name='user_for_comparison',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_subject_user_for_comparison', to=settings.AUTH_USER_MODEL),
        ),
    ]
