# Generated by Django 2.0 on 2019-09-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0045_usersubject_user_for_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='experiment',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experiment',
            name='methods',
            field=models.TextField(blank=True, null=True),
        ),
    ]
