# Generated by Django 2.0 on 2019-09-06 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0046_auto_20190905_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='data_are_public',
            field=models.BooleanField(default=False),
        ),
    ]
