# Generated by Django 2.0 on 2019-09-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0047_subject_data_are_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='citation',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
