# Generated by Django 2.0 on 2019-11-28 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0049_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='control_mean_before',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='control_n_before',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='data',
            name='control_sd_before',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='data',
            name='control_se_before',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='data',
            name='treatment_mean_before',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='treatment_n_before',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='data',
            name='treatment_sd_before',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='data',
            name='treatment_se_before',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
