# Generated by Django 2.0 on 2020-02-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0050_auto_20191128_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubject',
            name='can_edit_attributes',
            field=models.BooleanField(default=True),
        ),
    ]
