# Generated by Django 2.0 on 2020-03-23 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0051_usersubject_can_edit_attributes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attribute',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
