from django.contrib import admin
from .models import Publication, Intervention, Population, Design, Experiment, BroadCategory, Crop, Taxon, IUCNActionLevel1, IUCNActionLevel2, IUCNActionLevel3, IUCNHabitatLevel1, IUCNHabitatLevel2, IUCNThreatLevel1, IUCNThreatLevel2, ExperimentDesign, ExperimentBroadCategory, ExperimentCrop, ExperimentPopulation, ExperimentTaxon, ExperimentLatLong, ExperimentIUCNAction, ExperimentIUCNHabitat, ExperimentIUCNThreat, ExperimentPopulationOutcome

admin.site.register(Publication)
admin.site.register(Intervention)
admin.site.register(Population)
admin.site.register(Design)
admin.site.register(Experiment)
admin.site.register(BroadCategory)
admin.site.register(Crop)
admin.site.register(Taxon)
admin.site.register(IUCNActionLevel1)
admin.site.register(IUCNActionLevel2)
admin.site.register(IUCNActionLevel3)
admin.site.register(IUCNHabitatLevel1)
admin.site.register(IUCNHabitatLevel2)
admin.site.register(IUCNThreatLevel1)
admin.site.register(IUCNThreatLevel2)

# Intersection tables
admin.site.register(ExperimentDesign)
admin.site.register(ExperimentBroadCategory)
admin.site.register(ExperimentCrop)
admin.site.register(ExperimentTaxon)
admin.site.register(ExperimentPopulation)
admin.site.register(ExperimentIUCNAction)
admin.site.register(ExperimentIUCNHabitat)
admin.site.register(ExperimentIUCNThreat)
admin.site.register(ExperimentLatLong)
admin.site.register(ExperimentPopulationOutcome)
